language: node_js
before_script:
    - npm install -g gatsby-cli
node_js:
    - lts/*
deploy:
    provider: script
    skip-cleanup: true
    script: yarn install --frozen-lockfile && yarn run deploy
    keep-history: true
    on:
        branch: master
