language: node_js
before_script:
    - yarn global add gatsby-cli
node_js:
    - lts/*
deploy:
    provider: script
    skip-cleanup: true
    script: yarn install && yarn run deploy
    keep-history: true
    on:
        branch: master
